### ISSUE TITLE
When generating a world

### ISSUE THREAD

**Issue by awprice** [barneygale/cedar#1]
I am getting the following error when I go to generate a world.

C:\Users\Outlaw11A\Desktop\cedar-master\cedar-master>cedar.py
... creating temporary directory
... downloading jar
... writing server.properties
... initialising world
Traceback (most recent call last):
  File "C:\Users\Outlaw11A\Desktop\cedar-master\cedar-master\cedar.py", line 82,
 in <module>
    main(sys.argv[1:])
  File "C:\Users\Outlaw11A\Desktop\cedar-master\cedar-master\cedar.py", line 76,
 in main
    Cedar(**config)
  File "C:\Users\Outlaw11A\Desktop\cedar-master\cedar-master\cedar\cedar.py", li
ne 105, in **init**
    self.log(1, "saved as {0}".format(output))
  File "C:\Python27\lib\contextlib.py", line 35, in **exit**
    self.gen.throw(type, value, traceback)
  File "C:\Users\Outlaw11A\Desktop\cedar-master\cedar-master\cedar\cedar.py", li
ne 26, in tempdir
    shutil.rmtree(tmp)
  File "C:\Python27\lib\shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Python27\lib\shutil.py", line 254, in rmtree
    os.rmdir(path)
WindowsError: [Error 32] The process cannot access the file because it is being
used by another process: 'c:\users\outlaw~1\appdata\local\temp\cedar-tmp-b
bm4xl'

**Comment by awprice** [comment]
Is this being looked at?

**Comment by barneygale** [comment]
5 years late, but this is general Windows stupidness. You can probably modify the code to retry the `shutil.rmtree` on a timer. It might be better in newer Python versions.
